### ISSUE TITLE
CI: GitHub Actions

### ISSUE THREAD

**Issue by azu** [textlint/textlint#632]
We can move to GitHub Actions from Travis CI and Appveyor.

GitHub Action do 20 workflows concurrently.

> You can execute up to 20 workflows concurrently per repository.
> https://help.github.com/en/articles/about-github-actions

It will improve testing performance.

**Comment by azu** [comment]
Rough Image:

- Move Unit/E2E test to GitHub Action from Travis CI/Appveyor
  - Drop to use Appveyor
- Preserve deploy script on Travis CI

```yaml
name: "CI"
on: [push, pull_request]

jobs:
  unit_test:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        os: [macOS-10.14, windows-2016, ubuntu-18.04]
        node: [ 8, 10, 12 ]
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Bootstrap
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
          yarn run bootstrap
      - name: Run tests
        run: |
          yarn test
          yarn run test:examples
          yarn run test:integration
  documentation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 12 ]
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Bootstrap
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
          yarn run bootstrap --scope textlint-website
      - name: Check documents
        run: |
          yarn run test:docs
          yarn run website
```

It is difficult that move Deploy Script(Build Website and deploy to gh-pages) to GitHub Actions.

- https://github.com/textlint/textlint/blob/e77f213d0a4e71262935a6eb93979f2d100d5717/.travis.yml#L45-L54

Because `GITHUB_TOKEN` of GitHub Actions does not support gh-pages yet.

- [Cannot deploy with GITHUB_TOKEN for new repository · Issue #9 · peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages/issues/9)
